apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: px9a3c5ik-java-springboot 
  janus-idp.io/tekton: px9a3c5ik-java-springboot
  backstage.io/kubernetes-id: px9a3c5ik-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: px9a3c5ik-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  