apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: px9a3c5ik-java-springboot
  janus-idp.io/tekton: px9a3c5ik-java-springboot
  backstage.io/kubernetes-id: px9a3c5ik-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: px9a3c5ik-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
